# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=60)),
                ('goods_num', models.IntegerField()),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
