# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_goods_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='goods_num',
            field=models.IntegerField(default=0),
        ),
    ]
